### ISSUE TITLE
Modelado de BD: modelo entidad relación

### ISSUE THREAD

**Issue by soleforna** [soleforna/integrador_ISP#16]

**Comment by Matiasdlf01** [comment]
https://drive.google.com/drive/folders/1Du7Qfhv3uCScge8vyjsEQnc05JOhIxFn?usp=sharing

**Comment by Matiasdlf01** [comment]
https://drive.google.com/file/d/19Ynu3bKWJA0uQRnINOmLxgRGXEiVNYER/view
