### ISSUE TITLE
Definir historias de usuario

### ISSUE THREAD

**Issue by soleforna** [soleforna/integrador_ISP#2]
Acá dejaremos las historias de usuarios para darle forma a los requerimientos

**Comment by soleforna** [comment]
#US01: 
 **Como** cliente **puedo** reservar una mesa **para** no tener que llamar telefónicamente o esperar personalmente hasta que se desocupe una mesa

**Comment by acamus79** [comment]
#US01:
**Como dueño** del establecimiento gastronómico 
**quiero** ver al finalizar el día cuáles son las mesas que más facturaron y los mozos que más comandas generaron, 
**para** así poder mejorar la rotación del personal e incluso la ubicación de las mesas

**Comment by acamus79** [comment]
#US01:
**Como dueño** del establecimiento gastronómico
**me serviría** saber el tiempo desde el pedido hasta la comanda finalizada y servida, también el tiempo de uso de una mesa, y los rangos horarios de más consumo y facturación
**para** así organizar promociones (happy hour), que me sirvan **para** optimizar recursos

**Comment by soleforna** [comment]
#US08:

Como **dueño** del establecimiento gastronómico **quiero** conocer las reviews de mis clientes **para** mejorar los servicios prestados.

**Comment by soleforna** [comment]
#US09: 

Como **dueño** del establecimiento gastronómico **quiero** obtener una lista de subscriptores **para** poder enviar un email cada cierto tiempo para que el cliente no se olvide de nosotros y nos tenga en mente para salir a comer.

**Comment by soleforna** [comment]
#US10:

**Como** dueño del establecimiento gastronómico **quiero** implementar diferentes estrategias de fidelidad de mis clientes **para** fomentar la venta de determinado productos, fomentar visitas en determinados días u horarios o visitas en grupos.

**Comment by Ari-07x** [comment]
US6: COMO mozo que toma el pedido QUIERO que el menú desde el cual cargo cada pedido (bebida, comida, postre, etc) sea de acceso sencillo, es decir no más de 2 o 3(como mucho) clicks por producto, PARA que el proceso de carga de pedidos no demore más de lo que demoraría tomarlo sin la aplicación.
(Se apuntaría a una interfaz ágil en la toma de pedidos).

US7: COMO mozo que toma el pedido QUIERO que en caso de cometer un error al cargar un producto, éste pueda subsanarse rápidamente, sin necesidad de reiniciar la toma del pedido, PARA que sea ágil la corrección de errores.

**Comment by LucianoT123** [comment]
#US11:
Yo como propietario de un restaurante, quiero tener una aplicación móvil para que los mozos/as puedan tomar los pedidos de los clientes y así agilizarlos, y al mismo tiempo poder llevar un registro en tiempo real que quede asentado en el sistema del restaurante para poder hacer un control de stock de la mercadería al finalizar la jornada.

**Comment by Marquitos280419** [comment]
#US12
Yo como encargado de caja me gustaría podes hacer un reporte de todas las ventas efectuadas al final del día o en el día deseado.

**Comment by Matiasdlf01** [comment]
#US13
Yo como empleado, quiero tener un código propio para realizar mi respectivo cobro y así se agiliza todo.

**Comment by JoanaGM44** [comment]
#US14
Como cliente, me gustaría visualizar la cuenta a medida que voy seleccionando mi pedido.

**Comment by acamus79** [comment]
#US15

Como Mozo me gustaria que se pudiera contemplar las propinas como un porcentaje del ticket

**Comment by LucianoT123** [comment]
#US 16 Como propietario del restaurante, quiero tener una aplicación móvil, para poder llevar un registro en tiempo real que quede asentado en el sistema del restaurante, para poder hacer un control de stock de la mercadería al finalizar la jornada.

**Comment by acamus79** [comment]
#US17

Como Mozo me gustaría que las propinas fueran a un pozo del turno y poder repartirla con el resto del personal al finalizar el turno todas o incluso por quincena o mensual

**Comment by acamus79** [comment]
#US04

Como dueño del establecimiento gastronómico me gustaría poder diferenciar los pedidos o reservas que ingresan por PedidosYa o alguna plataforma similar

**Comment by leocas1** [comment]
#US05

Como Dueño del Establecimiento Gastronómico
me gustaría poder exportar el cierre de caja al Excel

**Comment by leocas1** [comment]
#US18
Como Mozo del Establecimiento Gastronomico
Me Gustaria poder entrar a la reserva del cliente y asignarle una mesa

**Comment by JoanaGM44** [comment]
#US19
Como propietario de un restaurante, quisiera poder actualizar el precios de los productos.

**Comment by JoanaGM44** [comment]
#US20

Como propietario, me gustaría visualizar estadísticas sobre los productos mas vendidos, flujo de ventas, ingresos-egresos, etc.

**Comment by Ari-07x** [comment]
US7: COMO mozo que toma el pedido QUIERO que en caso de cometer un error al cargar un producto, éste pueda subsanarse rápidamente, sin necesidad de reiniciar la toma del pedido, PARA que sea ágil la corrección de errores.

**Comment by Ari-07x** [comment]
#US21 Como CLIENTE me gustaria que no sea obligatorio tener un celular a los efectos de  ordenar mi pedido, PARA que pueda elegir si mi experiencia en un local gastronómico la gestiono con un dispositivo electrónico o sin el mismo.
